name: Tests-Conda

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6,3.7]

    steps:
      - name: Default encoding
        run: "[System.Text.Encoding]::Default"
        shell: powershell
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-verison }}
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run Tox
        run: tox -c tox_conda.ini -e py