name: Tests-Conda

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-verison }}
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-conda
      - name: Run Tox
        run: tox -e py